font: /usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf
fonts:
  思源黑体: /usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf
  霞鹜文楷: /usr/share/fonts/TTF/LXGWWenKai-Medium.ttf
latin_font: /usr/share/fonts/TTF/CaskaydiaCoveNerdFont-Regular.ttf
latin_fonts:
  Caskaydia Cove Nerd Font: /usr/share/fonts/TTF/CaskaydiaCoveNerdFont-Regular.ttf
  JetBrains Mono Nerd Font: /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf
  Noto Sans Mono: /usr/share/fonts/noto/NotoSansMono-Regular.ttf
  霞鹜文楷: /usr/share/fonts/TTF/LXGWWenKai-Medium.ttf
  思源黑体: /usr/share/fonts/adobe-source-han-sans/SourceHanSansCN-Regular.otf
library_dir: library.example
default_device: wall_panel
reward: {id: toy, name: 玩具, cost: 50, initial_points: 25}
checklists:
  person_1: [1, 2, 3]
  person_2: [6, 7, 8]
  family: [4, 5]

channels:
  home:
    mode: scheduled
    schedule:
      - {time: "12:00", item: 1}
      - {time: "13:00", item: 2}
    random_items: [1, 2, 3]

devices:
  wall_panel:
    profile: crowpanel_579
    channel: home
    refresh:
      minutes: 30
      active_start: "07:00"
      active_end: "22:00"
    presentation:
      status_bar:
        left: []
        center:
          - module: solar_term
        right:
          - module: weekday
      panels:
        - template: landscape_3
          slots:
            1: {module: images, collections: "plants,animals"}
            2: {module: items}
            3: {module: chinese, source: select}
        - template: landscape_1
          slots:
            1: {module: math, type: game24}
  kindleGen7dk:
    profile: kindle_6_167ppi_landscape
    channel: home
    refresh:
      minutes: 30
      active_start: "07:00"
      active_end: "22:00"
    presentation:
      status_bar:
        left:
          - module: solar_term
        center: []
        right:
          - module: weekday
      panel:
        template: landscape_5
        slots:
          1: {module: checklist, group: person_1}
          2: {module: checklist, group: person_2}
          3: {module: checklist, group: family, reward: toy}
          4: {module: images, collections: "*"}
